In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(x)

[['Indonesia' 34.0 22000.0]
 ['Malaysia' 27.0 48000.0]
 ['jepang' 20.0 54000.0]
 ['Malaysia' 28.0 61000.0]
 ['jepang' 50.0 nan]
 ['Indonesia' 25.0 52000.0]
 ['Malaysia' nan 35000.0]
 ['Indonesia' 28.0 49000.0]
 ['jepang' 50.0 83000.0]
 ['Indonesia' 37.0 67000.0]]


In [8]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [10]:
print(x)

[['Indonesia' 34.0 22000.0]
 ['Malaysia' 27.0 48000.0]
 ['jepang' 20.0 54000.0]
 ['Malaysia' 28.0 61000.0]
 ['jepang' 50.0 52333.333333333336]
 ['Indonesia' 25.0 52000.0]
 ['Malaysia' 33.22222222222222 35000.0]
 ['Indonesia' 28.0 49000.0]
 ['jepang' 50.0 83000.0]
 ['Indonesia' 37.0 67000.0]]


In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [12]:
print(x)

[[1.0 0.0 0.0 34.0 22000.0]
 [0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 20.0 54000.0]
 [0.0 1.0 0.0 28.0 61000.0]
 [0.0 0.0 1.0 50.0 52333.333333333336]
 [1.0 0.0 0.0 25.0 52000.0]
 [0.0 1.0 0.0 33.22222222222222 35000.0]
 [1.0 0.0 0.0 28.0 49000.0]
 [0.0 0.0 1.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [16]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [18]:
print(x_train)

[[0.0 1.0 0.0 33.22222222222222 35000.0]
 [0.0 0.0 1.0 50.0 52333.333333333336]
 [1.0 0.0 0.0 34.0 22000.0]
 [0.0 1.0 0.0 28.0 61000.0]
 [0.0 1.0 0.0 27.0 48000.0]
 [1.0 0.0 0.0 28.0 49000.0]
 [0.0 0.0 1.0 50.0 83000.0]
 [1.0 0.0 0.0 25.0 52000.0]]


In [22]:
print(y_train)

[0 1]


In [23]:
print(x_test)

[[0.0 0.0 1.0 20.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [27]:
print(y_test)

[0 1]


In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [29]:
print(x_train)

[[0.0 1.0 0.0 -0.12502393096223327 -0.9153315167018385]
 [0.0 0.0 1.0 1.6517867584775032 0.12221047498198917]
 [1.0 0.0 0.0 -0.04265522350476197 -1.6934880104647092]
 [0.0 1.0 0.0 -0.6780709667481114 0.6409814708239028]
 [0.0 1.0 0.0 -0.783973590622003 -0.13717502293896788]
 [1.0 0.0 0.0 -0.6780709667481114 -0.07731683111105475]
 [0.0 0.0 1.0 1.6517867584775032 1.9578616910379918]
 [1.0 0.0 0.0 -0.9957788383697862 0.10225774437268464]]


In [30]:
print(x_test)

[[0.0 0.0 1.0 -1.525291957739244 0.2219741280285109]
 [1.0 0.0 0.0 0.27505264811691277 1.0001306217913817]]
